baseURL = "http://localhost:1313"
canonifyURLs = true
enableRobotsTXT = true
landscapePhotoWidths = [2500, 1500, 1000]
languageCode = "pl"
portraitPhotoWidths = [1500, 1000, 750]
theme = "aw_saicos"
title = "saicos.pl"
[[menu.main]]
name = "Zastosowanie"
url = "#"
weight = 2
[outputs]
posts = ["HTML"]
section = ["JSON", "HTML"]
[permalinks]
"/" = "/:slug/"
categories = "/kategoria/:slug/"
do-wnetrz = "/do-wnetrz/:slug/"
na-zewnatrz = "/na-zewnatrz/:slug/"
porady-eksperta = "/:slug/"
produkty = "/:slug/"
[related]
includeNewer = true
threshold = 80
toLower = false
[[related.indices]]
name = "categories"
weight = 100
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[taxonomies]
category = "categories"
