baseURL = "http://localhost:1313"
canonifyURLs = true
enableRobotsTXT = true
landscapePhotoWidths = [2500, 1500, 1000]
languageCode = "pl"
portraitPhotoWidths = [1500, 1000, 750]
theme = "aw_saicos"
title = "saicos.pl"
[outputs]
section = ["JSON", "HTML"]
posts = ["HTML"]
[permalinks]
"/" = "/:slug/"
categories = "/kategoria/:slug/"
porady-eksperta = "/:slug/"
products = "/:slug/"
[related]
includeNewer = true
threshold = 80
toLower = false
[[related.indices]]
name = "categories"
weight = 100
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[taxonomies]
category = "categories"