---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/categories.yml
  label: Kategorie
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/products
  label: Produkty
  create: all
  match: "**/*"
  templates:
  - product
- type: directory
  path: content/na-zewnatrz
  label: Na zewnątrz
  create: all
  match: "**/*"
  templates:
  - zastosowanie-listowanie-zewnatrz
  - zastosowanie-pojedynczy
- type: directory
  path: content/do-wnetrz
  label: Do wnętrz
  create: all
  match: "**/*"
  templates:
  - zastosowanie-listowanie-wnetrz
  - zastosowanie-pojedynczy
- type: heading
  label: Ustawienia
- type: document
  path: data/footer.yml
  label: Stopka
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
