---
label: produkt
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: name
  label: name
- type: list
  name: categories
  label: categories
- type: file
  name: image
  label: image
- type: text
  name: alt
  label: alt
- type: text
  name: description
  label: description
- type: text
  name: slug
  label: slug
- name: kategorie
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: documents
      section: kategorie-6ee5f54c-c3a9-4f67-9f8f-84d08103eac5
      file: data/category.yml
      path: 
  label: Kategorie
