---
label: produkt
hide_body: true
fields:
- type: text
  name: name
  label: Nazwa - nagłówek
- name: subname
  type: text
  config:
    required: false
  label: Podpis pod nagłówkiem
- type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  name: description
  label: Opis produktu
- type: file
  name: image
  label: Zdjęcie produktu
- type: text
  name: alt
  label: Opis zdjęcia alt
- type: text
  name: slug
  label: slug
- name: categories
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: documents
      section: kategorie-64adb4ee-8399-4bad-8fea-d725f77a8f3d
      file: data/categories.yml
      path: categories
  label: Kategorie
- name: cechy
  type: field_group_list
  fields:
  - name: ikona
    type: file
    config:
      maxSize: 1
    label: Ikona
  - name: nazwa_cechy
    type: text
    config:
      required: false
    label: Nazwa cechy
  config:
    min: 
    max: 
    labelField: 
  label: Cechy
- name: header
  type: include
  config: {}
  template: header
  label: header
