---
label: produkt
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: name
  label: name
- type: file
  name: image
  label: image
- type: text
  name: alt
  label: alt
- type: text
  name: description
  label: description
- type: text
  name: slug
  label: slug
- name: kategorie
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: kategorie
      file: data/category.yml
      path: 
  label: Kategorie
