---
label: produkt
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: name
  label: Nazwa - nagłówek
- type: file
  name: image
  label: Zdjęcie produktu
- type: text
  name: alt
  label: alt
- type: text
  name: description
  label: Opis produktu
- type: text
  name: slug
  label: slug
- name: categories
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: documents
      section: kategorie-64adb4ee-8399-4bad-8fea-d725f77a8f3d
      file: data/categories.yml
      path: categories
  label: Kategorie
